version: '3.8'

services:
  uix-resume-builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_REDIRECT_URI: ${NEXT_PUBLIC_REDIRECT_URI:-http://localhost:3000/auth/linkedin/callback}
        NEXT_PUBLIC_LINKEDIN_CLIENT_ID: ${NEXT_PUBLIC_LINKEDIN_CLIENT_ID}
        NEXT_PUBLIC_GOOGLE_REDIRECT_URI: ${NEXT_PUBLIC_GOOGLE_REDIRECT_URI:-http://localhost:3000/auth/google/callback}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:-http://localhost:3002}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        NEXT_PUBLIC_LINKEDIN_CLIENT_SECRET: ${NEXT_PUBLIC_LINKEDIN_CLIENT_SECRET}
        NEXT_PUBLIC_MIXPANEL_TOKEN: ${NEXT_PUBLIC_MIXPANEL_TOKEN}
        NEXT_PUBLIC_ENV: ${NEXT_PUBLIC_ENV}
    ports:
      - "3000:3000"
    restart: unless-stopped
